### ISSUE TITLE
Stereo labels after pasting display incorrectly

### ISSUE THREAD

**Issue by KseniiaSemenishcheva** [epam/ketcher#194] opened 2020-12-21 06:56 UTC
**Affected Versions:** _release, Standalone, Remote_
**Steps to Reproduce:**
1) Launch Ketcher.
2) Create any structure with stereobonds or open 
[Stereostructure.zip](https://github.com/epam/ketcher/files/5722729/Stereostructure.zip)
3) Click on the 'Calculate CIP' button of the main toolbar.
4) Select structure and copy using 'Copy' button or Ctrl+C hotkey.
5) Paste structure on canvas using 'Paste' button or Ctrl+V hotkey.
6) Select structure and cut using 'Cut' button or Ctrl+X hotkey.
7) Paste structure on canvas using 'Paste' button or Ctrl+V hotkey.

**Expected Result:**
Stereo labels should appear near stereobonds after 'Calculate CIP' action.
Stereo labels should disappear after paste of structure on canvas.

**Actual Result:**
Stereo labels displays on pasted structure with incorrect location.
![stereoLabels](https://user-images.githubusercontent.com/75974465/102748166-b6f87100-4372-11eb-941b-c91accc3654c.jpg)

**Comment by Svetlana-Asinovskaia** [comment] 2021-06-09 10:14
"Paste" doesn't work correct.
_Expected result:_ It's possible to select a place on the canvas to paste the structure.
_Actual result:_ The structure is copied to a place where the cursor is located. Console errors appear until the canvas is clicked after the "Paste" action.
![2021-06-09_13h10_18](https://user-images.githubusercontent.com/80695128/121336786-84dcca80-c924-11eb-977f-67396ac5860e.gif)

**Comment by Svetlana-Asinovskaia** [comment] 2021-06-10 14:46
Release/2.3 The issue is closed as fixed. Expected result "Stereo labels should disappear after paste of structure on canvas" is invalid.

**Closed by Svetlana-Asinovskaia** 2021-06-10 14:46 UTC
Labels: bug, epic: enhanced stereochemistry
