### ISSUE TITLE
The selected file format in the Save Structure window doesn't match the mockup

### ISSUE THREAD

**Issue by ZhannaNovikova** [epam/ketcher#1456] opened 2022-04-14 18:48 UTC
**Steps to Reproduce:**
	1. Launch the Ketcher
	2. Create structure 
	3. Open the "Save Structure" dialog by clicking on the "Save As" icon on the top menu
	4. Extend the "File format" drop down 
	
**Expected behavior:**
The selected file format in the Save Structure window matches the mockup
![image](https://user-images.githubusercontent.com/103422815/163455385-ce086638-4d9f-4f4c-a579-ebead300db70.png)

**Actual behavior:**
The selected file format in the Save Structure window doesn't match the mockup
![image](https://user-images.githubusercontent.com/103422815/163455616-38696626-4880-4916-a2e0-25f4a237a86d.png)

OS: [Microsoft Windows]
Browsers: Google Chrome: Version 100.0.4896.75/FireFox: Version 99.0 (64-bit)
Ketcher v2.4.2-183-g60a3caa7

**Comment by Nitvex** [comment] 2023-01-13 14:53
Issue is reproduced in v2.7.0-rc.9, moving to v2.9.0-rc.1

**Comment by KonstantinEpam23** [comment] 2023-02-01 10:26
@Nitvex looks like this is already fixed in 2.7.0:
<img width="511" alt="Screenshot 2023-02-01 at 11 19 56" src="https://user-images.githubusercontent.com/101649391/216017517-af0501ec-c653-4f76-9040-c6360b925271.png">

**Comment by yuleicul** [comment] 2023-02-13 11:36
**Steps to Reproduce**
1. Select tool _Selection_
2. Double-click on a bond or an atom

**Actual behavior**
App crashes

**Expected behavior**
Bond or Atom Properties Modal shows up

**Screenshots**
![ketcher-edit-bug-1](https://user-images.githubusercontent.com/27288153/218370300-b7db6680-8d4a-491b-b492-9f542bed3a9d.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 109.0.5414.120 (Official Build) (64-bit)

**Ketcher version** [e.g. v2.4.2]. 
Master branch

**Closed** 2023-02-13 13:51 UTC
Labels: bug, epic: new ux/ui
