### ISSUE TITLE
In Template Library scroll bar jumps up and down when it is centered

### ISSUE THREAD

**Issue by ElenaKlepova** [epam/ketcher#184] opened 2020-12-16 21:38 UTC
**Description:**
When Template Library is opened, the scroll bar jumps up and down when it is centered. 

**Steps to reproduce:**
1. Click Custom Templates button.
2. Hover over the scroll bar.
3. Drag the scroll bar to the center.

**Actual result:**
When the scroll bar is centered, it jumps up and down.
![2020-12-17_00h21_47](https://user-images.githubusercontent.com/75974843/102409071-82e22080-3fff-11eb-8b0b-0b80c5a9f387.gif)

**Expected result:**
When the scroll bar is centered, it does not move.

**Comment by AndreiMazol** [comment] 2021-03-22 13:50
Cannot reproduce.

**Comment by Svetlana-Asinovskaia** [comment] 2021-03-26 08:40
Release/2.2 Issue is closed as fixed

**Closed** 2021-04-15 13:00 UTC
Labels: bug
