### ISSUE TITLE
 Unable to save a reaction in server formats if text is present on the canvas

### ISSUE THREAD

**Issue by ZhannaNovikova** [epam/ketcher#1444] opened 2022-04-14 07:03 UTC
**Steps to Reproduce **
1. Launch Ketcher
2. Create 2 structures
3. Add the reaction arrow between them using the "Arrow Open Angle Tool" on the left menu
4. Add a text using the "Add Text" on the left menu
5. Click on the "Save as..." icon on the top menu
6. Select any server format (e.g. MDL Rxnfile V3000) in the "File format" drop down

**Expected behavior**
The "Save Structure" dialog is opened successfully, without any errors for all File formats (The format is selected. It’s possible to save the file)

**Actual behavior **

Remote mode:

Error message “Convert error! struct data not recognized as molecule, query, reaction or reaction query”  is displayed. 400 HTTP code is gotten.
With “SVG Document” and “PNG Image” formats the error message is not displayed. The 400 HTTP code is gotten after clicking on the “Save” button with the following description:
{
"error": "'struct data not recognized as molecule, query, reaction or reaction query'"
}

Standalone mode: The error message “Given string could not be loaded as (query or plain) molecule or reaction, see the error messages: 'reaction KET loader: Unknown reaction node: text', 'reaction KET loader: Unknown reaction node: text', 'molecule auto loader: Arrow nodes supported only for reactions', 'molecule auto loader: Arrow nodes supported only for reactions'" is displayed in the pop up window.

![image](https://user-images.githubusercontent.com/103422815/163193964-57dd5165-fee3-4dc3-97ce-95931bef314f.png)

OS: [Microsoft Windows]
Browsers: Google Chrome: Version 100.0.4896.75/FireFox: Version 99.0 (64-bit)
Ketcher v2.4.2-158-g2312c8e8

**Comment by ZhannaNovikova** [comment] 2022-04-14 07:13
Related issue in the Indigo: https://github.com/epam/Indigo/issues/705

**Comment by even1024** [comment] 2022-04-19 00:06
Cannot reproduce it. Must be fixed in 1.6.3.

**Closed** 2022-04-19 07:51 UTC
Labels: bug, external

**Comment by ZhannaNovikova** [comment] 2022-04-20 08:26
Verified as fixed in the Version 1.6.5.0-g0e5aaceee-wasm32-wasm-clang-13.0.0

**Comment by ZhannaNovikova** [comment] 2022-05-13 12:27
Verified as fixed in the Standalone mode (Release 2.5.0).
The issue related to the Remote mode will be fixed in the [indigo-1.7] milestone.

**Comment by ZhannaNovikova** [comment] 2022-05-23 09:42
Verified as fixed on Release 2.5.0.
