### ISSUE TITLE
calling ReactDOMClient.createRoot() on a container that has already been passed to createRoot() before

### ISSUE THREAD

**Issue by hellhorse123** [epam/ketcher#3800] opened 2023-12-26 07:42 UTC
When i try to create React component with ketcher, I get white screen and error:

<img width="503" alt="Screenshot 2023-12-26 at 10 39 47" src="https://github.com/epam/ketcher/assets/48678379/f798582b-081b-49a1-899c-1291dabfe4e3">

```
import {
  Ketcher,
  RemoteStructServiceProvider,


  StructServiceProvider,
} from 'ketcher-core';
import { Editor } from 'ketcher-react';
import { useState } from 'react';

let structServiceProvider: StructServiceProvider =
  new RemoteStructServiceProvider(
    process.env.API_PATH || process.env.REACT_APP_API_PATH || '',
  );

const MyComponent = () => {
  const [hasError, setHasError] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');
  return (
    <Editor
      staticResourcesUrl={process.env.PUBLIC_URL}
      structServiceProvider={structServiceProvider}
      errorHandler={(message: string) => {
        setHasError(true);
        setErrorMessage(message.toString());
      }}
      onInit={(ketcher: Ketcher) => {
        //@ts-ignore
        window.ketcher = ketcher;

        window.parent.postMessage(
          {
            eventType: 'init',
          },
          '*',
        );
      }}
    />
  );
};

export default MyComponent;

```

**Comment by DoaaRadwan** [comment] 2024-08-15 12:08
any updates on this issue ?

**Comment by shikharsg** [comment] 2024-09-08 14:40
👍 to this bug report, been trying to get it work since 3 days, and found that for now a quick temporary fix is go back a few versions:

`npm install ketcher-standalone@2.13.0 ketcher-react@2.13.0 ketcher-core@2.13.0 --save`

and while the warning still happens, the editor does work!

But would love to see this fixed!

p.s. really loving Ketcher and the fact that it's open source!

**Comment by rrodionov91** [comment] 2024-09-09 11:53
Hi @hellhorse123 and @shikharsg 
Issue was reproducing only in strict mode and was fixed in 2.24.0-rc.1. Related ticket https://github.com/epam/ketcher/issues/4979 
We are working on public release of 2.24 and planning to publish it on this week.

**Comment by rrodionov91** [comment] 2024-09-09 11:54
Close as duplicate of https://github.com/epam/ketcher/issues/4979

**Closed by rrodionov91** 2024-09-09 11:54 UTC
Labels: bug

**Comment by shikharsg** [comment] 2024-09-09 12:37
Thanks @rrodionov91 !
