### ISSUE TITLE
The attachment points R, to which the bond was attached, change randomly, when pasting onto the canvas

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#4901] opened 2024-06-26 15:15 UTC
**Steps to Reproduce**
1.	Open this file  [For AP in Macro.zip](https://github.com/user-attachments/files/15991115/For.AP.in.Macro.zip)
 
       <img width="474" alt="image" src="https://github.com/epam/ketcher/assets/139227567/caa4c094-7299-486f-b912-752ca4a75ba8">

2.	Switch to the Macro mode and draw bonds:
- from AP R1 of structure F2 to AP R2 of structure F3
- from AP R1 of structure F3 to AP R2 of structure F4
 
     <img width="418" alt="image" src="https://github.com/epam/ketcher/assets/139227567/e65bfaad-c398-45bc-90ca-46bea291438b">

3.	Copy these structures and paste them nearby

**Actual behavior**
The attachment points R, to which the bond was attached, change randomly

<img width="418" alt="image" src="https://github.com/epam/ketcher/assets/139227567/9f65bb2c-429f-4043-a2f9-2d08163c0f04">

**Expected behavior**
After pasting, the attachment points R should not change

**Screenshots**

https://github.com/epam/ketcher/assets/139227567/cb817547-13cf-43a4-a85a-f2bead856702

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (125.0.6422.142) x64

**Ketcher version** 2.22.0-rc.7, Build at 2024-06-20; 18:42:41

Issue found while testing https://github.com/epam/ketcher/issues/4530

**Comment by rrodionov91** [comment] 2024-08-07 13:53
It happens because structure has several attachment points on one atom. Ketcher loses information about exact leaving group atom after serialisation and take attachment points consequently. So I would say that it is expected behaviour.
Closing ticket, please reopen if something wrong.

**Closed as not planned by rrodionov91** 2024-08-07 13:53 UTC
Labels: Priority: High, Macromolecules, Macro-Micro

**Comment by AlexeyGirin** [comment] 2024-08-08 15:50
Closed by @AlexanderSavelyev decision after discussion
