### ISSUE TITLE
Label Display At Stereogenic Centers for the STEREO FLAGS and STEREO MARKS

### ISSUE THREAD

**Issue by Vesdet** [epam/ketcher#63] opened 2020-10-12 13:38 UTC
As a Ketcher collaborator I'd like to implement the following settings for enhanced stereochemistry in Ketcher.

Specifies how labels for stereogroups are displayed at individual tetrahedral stereogenic centers.
IUPAC Style (should be selected by default)
Classic
On
Off
The following table shows the four options:
![display-labels](https://user-images.githubusercontent.com/14963002/95752814-49accd80-0ca9-11eb-838d-8e12aa121562.PNG)

Part 3 in Epic #56

**Comment by Svetlana-Asinovskaia** [comment] 2021-05-17 09:59
The description of the task has been updated. The possibility to change the name of the Stereo flags will be implemented within the task https://github.com/epam/ketcher/issues/518

**Comment by Svetlana-Asinovskaia** [comment] 2021-05-24 12:04
Expected result: By default, all stereogenic centers at the narrow end of the Single Up or Down bonds are assigned to the ABS stereogroup. The 'ABS' radiobutton is checked in the "Enhanced stereochemistry" window.

Actual result: If a structure is created on the canvas (not uploaded or selected from the 'Custom Templates') all the stereocenters are assigned to the 'AND' Group. The 'AND' radiobutton is checked in the "Enhanced stereochemistry" window.
![2021-05-24_15h02_51](https://user-images.githubusercontent.com/80695128/119345195-39c68480-bca1-11eb-96d7-1d61242b3b0f.gif)

**Closed** 2021-05-26 13:18 UTC
Labels: enhancement, epic: enhanced stereochemistry

**Comment by Svetlana-Asinovskaia** [comment] 2021-05-28 14:57
Release/2.3 The issue is verified and closed.
