### ISSUE TITLE
Stereo Labels and Stereo Flags for structures without stereocenters

### ISSUE THREAD

**Issue by Vesdet** [epam/ketcher#59] opened 2020-10-12 13:13 UTC
In some cases atoms shouldn't have Stereo Labels and Stereo Flags and shouldn't be marked. For example, see screenshots: 
![cyclohexane](https://user-images.githubusercontent.com/14963002/95750370-b625cd80-0ca5-11eb-9ddf-00efea17e65f.jpg)
![unsteric](https://user-images.githubusercontent.com/14963002/95750380-b8882780-0ca5-11eb-8248-8b2c2ffc26c6.jpg)

These molecules don't have any stereocenters.

The user should have a possibility to turn off Stereo Labels and Stereo Flags for structures without stereocenters. Or Ketcher should automatically calculate if the atom is steric or not in order to mark only steric atoms and structures.

Epic link: #56

**Comment by Svetlana-Asinovskaia** [comment] 2021-06-03 12:57
Release/2.3 The issue is closed as duplicate. It will be fixed in https://github.com/epam/ketcher/issues/418

**Closed** 2021-06-03 15:34 UTC
Labels: duplicate, enhancement, epic: enhanced stereochemistry
