### ISSUE TITLE
Copy drawing to the clipboard as an image

### ISSUE THREAD

**Issue by AndreiMazol** [epam/ketcher#691] opened 2021-07-23 12:22 UTC
It is necessary to copy structure as png to  clipboard in order to provide possibility to  insert it to Word/PowerPoint. This functionality should be available by pressing a new hotkey (please discuss it with @nseufulina  and @AlexanderSavelyev )

**Comment by nseufulina** [comment] 2021-07-26 15:11
Cntr+B hotkey is available for this shortcut

**Comment by nseufulina** [comment] 2021-08-05 15:27
Need to verify if those are bugs to fix:

**1)No alert in Opera**
Opera 77.0.4054.277 Standalone mode

Steps:
1. Draw an object on the canvas.
2. Select object.
3. Click "Copy Image" or click "Ctrl+Shift+F"

Expected result:
Modal window with alert "This feature is not available in your browser" appears.

Actual result:
Modal window does not appear.


**2)No alert in the remote mode**
Opera 77.0.4054.277 Remote mode
FireFox 90.0 Remote mode

Steps:
1. Draw an object on the canvas.
2. Select object.
3. Click "Copy Image" or click "Ctrl+Shift+F"

Expected result:
Modal window with alert "This feature is not available in your browser" appears.

Actual result:
Modal window does not appear.

**3)Copied objects are displayed as black squares in the Clipboard.** 
Steps:
1. Draw objects on the canvas
2. Select object
3. Click "Copy Image" or click "Ctrl+Shift+F"
4. Open Word (or any pplication to paste)
5. Open Clipboard (Win+V)

Expected result:
Objects are displayed as copied structures.

Actual result:
Objects are displayed as black squares.
![image](https://user-images.githubusercontent.com/87320094/128374385-55144b3c-1126-4970-9ec2-c49815ea13bb.png)


**4)Objects from Clipboard are pasted incorrectly from the Clipboard.**
_Scenario1:_
Steps:

1. Create two structures on the canvas.
2. Select first structure and click Copy Image button.
3. Select second structure and click Copy Image button.
4. Open Word/PowerPoint.
5. Open Clipboard (Win+V).
6. Click on the object which is second from the top of the list.

Expected result:
Object is pasted.

Actual result:
Black square is pasted.

_Scenario2:_
Steps:

1. Create two structures on the canvas.
2. Select first structure and click Copy Image button.
3. Select second structure and click Copy Image button.
4. Open Word/PowerPoint.
5. Open Clipboard (Win+V).
6. Click on the object which is second from the top of the list.
7. Click on the object which is first from the top of the list.

Expected result:
Objects are pasted.

Actual result:
Black squares are pasted.

**Comment by nseufulina** [comment] 2021-08-11 09:40
Copy Image action does not work with structures with dative/hydrogen bonds. Should be fixed by #668 
Release 2.4 The issue is verified and closed.

**Comment by nseufulina** [comment] 2021-08-13 13:32
Possible bugs:

**1.When structure has Generic S-Group, saved structure does not have brackets**

Steps:
1. Draw any structure 
2. Select S-Group button
3. Select part or whole structure 
4. Click 'OK' (generic s-group)
5. Copy Image

Expected result:
Structure, pasted in another application is the same as in the Kethcer.
![image](https://user-images.githubusercontent.com/87320094/129359886-85236b75-9c5a-438a-a193-ebc1a58dff9e.png)
Actual result:
Structure, pasted in another application does not have brackets.
![image](https://user-images.githubusercontent.com/87320094/129360023-b18a1446-cc43-46c9-91c2-041507b926f7.png)


**2.Structure with R-group can not be saved if only one structure is selected**

Steps:
1. Draw any structure
2. Select R-Group Fragment Tool
3. Select structure and choose any R-label
4. Copy Image 
5. Create another structure on the canvas
6. Select structure with R-Group and Copy Image
7. Select both structures and Copy Image

Actual result:
step 4 - empty image is copied and pasted.
step 6 - empty image is copied and pasted.
step 7 - structures are copied and pasted.

**3.Structure with R-group is saved without brackets**

Step 7 from the previous paragraph.
Actual result:
Structure with R-Group does not have brackets
Ketcher: ![image](https://user-images.githubusercontent.com/87320094/129361053-8b9af058-e6d1-48e6-abaa-708d18cf92b1.png)
Redactor: ![image](https://user-images.githubusercontent.com/87320094/129360991-54ecc925-b08f-4c89-8735-959c1d4d41dc.png)

**4.Attachment point view is different from the Ketcher**

Steps:

1. Create any structure
2. Select Attachment Point Tool
3. Click on any atom of the structure and choose any attachment point
4. Copy Image 

Different attachment point presentation:
Ketcher: ![image](https://user-images.githubusercontent.com/87320094/129361416-8d72c303-2923-41a8-88b8-613a94321421.png)
Redactor: ![image](https://user-images.githubusercontent.com/87320094/129361445-cfbded46-8ab0-4712-848c-284b3fcab5c7.png)


**5.Can't save structure with some atom generics.**

Steps:

1. Create any structure
2. Click Periodic Table button and Extended tab
3. Choose AH in atom generics section
4. Click on the structure's atom
5. Copy Image

Actual result:
Structure is not saved. 

Addiction:
The same behavior with AH, QH, M, MH, XH atom generics. 

**6.Saved bonds does not have Reacting Center marks.**

Steps:

1. Draw any structure.
2. Double-click structure's bond.
3. Select any Reacting Center option and click ok
4. Copy Image

Expected result:
Reacting Center mark is displayed in the saved structure.

Actual result:
Reacting Center mark is not saved.

Ketcher: ![image](https://user-images.githubusercontent.com/87320094/129362688-f66d7e13-e32f-4542-8dc1-e884acd256c0.png)
Redactor: 
![image](https://user-images.githubusercontent.com/87320094/129362767-ff6005fb-2911-41ab-8806-f34f87e8a9ca.png)

**7.Atom's properties.**

Steps:

1. Draw any structure
2. Double-click structure's atom

3. When inversion type is chosen in the atom's properties, it is not saved.
![image](https://user-images.githubusercontent.com/87320094/129363144-7bb3c550-4bd8-4374-bf59-e15a4abf06c2.png)
![image](https://user-images.githubusercontent.com/87320094/129363185-4aac782f-6ea0-4353-b5b9-4ef03d762007.png)

4.  When any property is chosen for the atom with alias, atoms name is displayed
Before chosing isotope and after
![image](https://user-images.githubusercontent.com/87320094/129363878-1800c543-361b-4bbd-94c0-800b8d728d0f.png)

5. When H count is chosen in the atom's properties, representation of properties is changed
Before H-count
![image](https://user-images.githubusercontent.com/87320094/129363557-349ee9aa-ca24-43f2-8f2f-0206a9158d8a.png)
After H-count
![image](https://user-images.githubusercontent.com/87320094/129363603-64f7e6eb-18d5-4033-b2da-07394a23a9d3.png)

**8.Stereochemistry labels are not saved**

Steps:

1. Create any structure
2. Add Single Up bond to the structure's atom
3. Copy Image
4. Click Calculate CIP
5. Copy Image

No label are pasted with saved structure

**Closed** 2021-08-17 09:17 UTC
Labels: enhancement

**Comment by nseufulina** [comment] 2021-08-17 10:37
Bugs are external and should be fixed in scope of #720  
Release 2.4 The issue is verified and closed.
