### ISSUE TITLE
getComputedStyle Error when parameter 1 is not of type 'Element'

### ISSUE THREAD

**Issue by japhill** [epam/ketcher#248] opened 2021-01-16 02:43 UTC
I embedding this component into  a webcomponent.  when I click an atom button on the right side of the window or on the bottom outside of the canvase, the listener checks to see if I clicked on an element.  But as it traverses the item, it assumes they are all elements.  It has something to do with the shadowdom and #docfragment or something like that.

could you add a check to make sure it's an element so the javascript error is not thrown?

I am attaching screenshots.
1.  first image shows where I click
2. second image shows the error message in console
![Screen Shot 2021-01-15 at 9 38 45 PM](https://user-images.githubusercontent.com/29437720/104795235-aa511800-577a-11eb-8f5a-eb7b069309e3.png)
![Screen Shot 2021-01-15 at 9 34 21 PM](https://user-images.githubusercontent.com/29437720/104795238-af15cc00-577a-11eb-92d6-45e9030b826c.png)
![Screen Shot 2021-01-15 at 9 34 55 PM](https://user-images.githubusercontent.com/29437720/104795244-b3da8000-577a-11eb-9855-0d6b5466020a.png)

**Comment by AndreiMazol** [comment] 2021-01-19 11:50
Dear @japhill ,

thank you for your interest to Ketcher.

Your issue looks like a bug so  we will fix in the nearest release.

Best regards,
Ketcher team

**Comment by japhill** [comment] 2021-01-19 13:04
Thank you for looking into this.  FYI.  This is only a problem if I use the component in a webcomponent.  Tell the webcomponent to not use shadowroot…this is not a problem.

Jason Phillips  |  Software Developer  |  www.sciome.com<http://www.sciome.com/>
[/var/folders/74/zvdvmcbs5f37z0bln2b568tw0000gn/T/com.microsoft.Outlook/WebArchiveCopyPasteTempFiles/cidimage001.jpg@01D42EF8.0FD01810]

**Comment by AndreiMazol** [comment] 2021-01-19 13:16
Dear Jason, 

Anyway I made some changes,  please check  if it works for you

Best regards,
Andrei

**Comment by KseniiaSemenishcheva** [comment] 2021-01-20 07:21
Issue was tested by QA, closed as fixed. If issue reproduces on author's side issue will be reopened.

**Closed by KseniiaSemenishcheva** 2021-01-20 07:21 UTC
Labels: bug
