### ISSUE TITLE
Incorrect brackets rendering with S-Group and Functional Group

### ISSUE THREAD

**Issue by vitalgerko** [epam/ketcher#899] opened 2021-10-29 13:35 UTC
**Steps to Reproduce**
1. Launch Ketcher with the following display settings (settings: 'Atoms', 'Show hydrogen labels' - on).
2. Create chain structure.
3. Create S-Group using previously added chain.
4. Add on canvas FG (C2H5 for example) and Expanded FG abbreviation.

**Expected behavior**
All structures are inside the brackets.

**Actual behavior**

![Incorrect brackets rendering with S-Group and Functional Group](https://user-images.githubusercontent.com/90637536/139444458-31fce63f-3d8e-4e03-b675-33cf9ad049e7.png)

**Desktop:**
OS: Windows 10
Browser: Chrome Version 93.0.4577.63, Firefox Version 92.0, Microsoft Edge Version 93.0.961.47

**Comment by ansivgit** [comment] 2022-05-13 09:48
![01](https://user-images.githubusercontent.com/56927722/168257083-75a5913c-0161-49e2-a415-93b5c83ba208.jpg) ![02](https://user-images.githubusercontent.com/56927722/168257089-6f03c9c3-a4aa-4487-9b02-60eb34ddd239.jpg)

As you can see in the pictures, the position of the brackets does not depend on the structures and their width, but on the svg elements that highlight the structures

**Comment by KonstantinEpam23** [comment] 2023-01-26 16:54
This should be resolved by: https://github.com/epam/ketcher/pull/2125

**Comment by KonstantinEpam23** [comment] 2023-02-03 09:59
Closing as a duplicate of https://github.com/epam/ketcher/issues/2033

**Closed by KonstantinEpam23** 2023-02-03 09:59 UTC
Labels: bug, priority: low
