### ISSUE TITLE
How do I get a ketcher instance in react project?

### ISSUE THREAD

**Issue by ShiXuanP** [epam/ketcher#1898] opened 2022-12-08 11:00 UTC
How do I get a ketcher instance in react project?

![image](https://user-images.githubusercontent.com/113485241/206430109-f25a88a1-680b-4875-9f47-42262e2e5cbd.png)

**Comment by Nitvex** [comment] 2022-12-08 12:49
Closing this as duplicate of https://github.com/epam/ketcher/issues/1885

**Closed by Nitvex** 2022-12-08 12:49 UTC
