### ISSUE TITLE
Unclear/inconsistent handling of absolute/relative stereochemistry

### ISSUE THREAD

**Issue by sharped-rsc** [epam/ketcher#290] opened 2021-02-04 17:45 UTC
Hi,

I'm trying to find a way to allow users to draw chemical structures with absolute stereochemistry in ketcher and get the structures out as mol files - I've so far not found how to do this so I would appreciate any help or advice you are able to provide.

While trying to find the answer I've explored the Ketcher 2.0 demo page 
 https://lifescience.opensource.epam.com/ketcher/demo.html) current spec:
- Ketcher - version2.1.0-beta, build at 2021-01-11T13:54:16
- Indigo Toolkit - version1.3.0beta, build #355-g4846731c linux64

I would appreciate any help you are able to provide.

Dave

**Comment by AlexanderSavelyev** [comment] 2021-02-09 13:35
@sharped-rsc  could you please clarify your question. Do you want to add enhanced stereo information with ABS labels for the structures?

**Comment by sharped-rsc** [comment] 2021-02-10 13:01
HI @AlexanderSavelyev , thanks. So I have a lot of feedback that I was originally going to put in the card - hence the slightly odd title. 
![image](https://user-images.githubusercontent.com/40824252/107493590-b23b8680-6b85-11eb-9038-ad679b545006.png) 
But principally - if a user draws L-alanine into the sketcher - I'd like to be able to have the ability to get the molfile from that and use that in a search. As a user I'd expect the search (and by implication the molfile) to be specifically about the enantiomer that I've drawn and not either enantiomer - ie the chiral flag should be set in the molfile)

In terms of my other feedback which is mainly UX and related points around the stereochemistry - would it make sense to add them as comments to this card, open a new card, or send an email to a mailing list?

Thanks for your help.

Dave

**Comment by sharped-rsc** [comment] 2021-02-15 14:08
Hi @AlexanderSavelyev,
Was my explanation sufficient and clear, or do you need more details?

Kind regards,
Dave

**Comment by AlexanderSavelyev** [comment] 2021-02-26 12:55
Hi @sharped-rsc  

Yes the explanation is clear. Right now we are in progress of implementing enhanced stereochemistry support, and this case should be covered by #56  epic

**Comment by sharped-rsc** [comment] 2021-02-26 14:17
Thanks for the update. Would it be ok if I add some comments to some of the cards in that epic?

**Comment by AndreiMazol** [comment] 2021-03-09 14:50
@sharped-rsc  I have linked your issue to #56  so no needs to add any additional information to the epic.

**Comment by Svetlana-Asinovskaia** [comment] 2021-06-02 08:58
Mol V2000 doesn’t support enhanced stereochemistry. In case a user saves a structure with the enhanced stereochemistry features in Molfile V2000 the warning “Structure contains enhanced stereochemistry features. Information will be partly lost” appears. 

After saving in Molfile V2000 Stereo Flags are displayed as follows:

- If all saved structures had ABS (Chiral) Flags, they will be present on the canvas after the saved file is opened.
- If one of the saved structures had the ABS (Chiral) Flag, then after opening the saved file, all structures will be displayed with the ABS (chiral) Flags.
- If none of the structures had the ABS (Chiral) Flag, then after opening the saved file, all structures will be displayed with the AND Enantiomer Flags.

The issue was discussed with @AlexanderSavelyev

**Closed** 2021-06-02 12:51 UTC
Labels: epic: enhanced stereochemistry, feature request

**Comment by Svetlana-Asinovskaia** [comment] 2021-06-03 07:19
Release/ 2.3 The issue is verified and closed.
