### ISSUE TITLE
A structure is not pasted on the canvas with Ctrl+V hotkey after clicking the 'Paste' button

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#1268] opened 2022-02-17 07:53 UTC
**Steps to Reproduce**
1. Create any structure on the canvas.
2. Select it with any selection tool.
3. Click the 'Cut' button.
4. Click the 'Paste' button.
5. Close the 'Error message' window.
6. Click Ctrl+V.

**Expected behavior**
The structure is pasted on the canvas.

**Actual behavior**
Canvas remains empty.

**Screenshots**
![2022-02-17_10h48_16](https://user-images.githubusercontent.com/80695128/154429726-3cd6ab20-d98e-4e47-b90e-97516a30a9dc.gif)

Desktop:

OS: Windows 10
Browser: Chrome, Version 98.0.4758.82
Ketcher version: v2.4.1-1-g759a4c01

**Comment by AndreiMazol** [comment] 2022-02-17 09:30
duplicate of #1267

**Closed by AndreiMazol** 2022-02-17 09:30 UTC
Labels: bug, duplicate, priority: high
