### ISSUE TITLE
Can't use Ketcher on Next JS application

### ISSUE THREAD

**Issue by michelmar** [epam/ketcher#2197] opened 2023-02-09 13:59 UTC
When I tried to load Ketcher on a Next JS application I get the message bellow:

`../node_modules/draft-js/dist/Draft.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: ../node_modules/ketcher-react/dist/index.modern.js
 `
I think this is related to : 
https://github.com/vercel/next.js/issues/19936

Could you provide a way to make this awesome library work with nextjs?

**Desktop (please complete the following information):**
 - OS: [e.g. iOS13.1]
 - Browser [chrome]

**Ketcher version** [e.g. v2.7.2].

**Comment by ahmepham** [comment] 2023-02-17 22:16
Hello!  I have the exact same problem, any updates on this?

**Comment by ahmepham** [comment] 2023-02-21 16:13
@Nitvex I was wondering if this is something that you are planning to address in the next little while.  Thanks!

**Comment by michelmar** [comment] 2023-03-23 10:27
Is there a chance this to be included in your roadmap?

**Comment by OliverDudgeon** [comment] 2023-03-24 11:04
I have it working in a NextJS app. Share what you're doing and I might be able to help.

**Comment by Nitvex** [comment] 2023-03-24 11:18
@ahmepham and @michelmar 
Thanks for reporting this. 
Unfortunately, we don't have plans to work on your request in the nearest future.
We can add it to our backlog, but I can not provide you exact date when issue will be resolved.

@OliverDudgeon 
If you have a solution for the problem, you are more than welcome.

**Comment by michelmar** [comment] 2023-05-22 11:07
@OliverDudgeon , I think utilizing the new Pages API available in the latest version to effectively use Ketcher. Without it, you may encounter the error mentioned earlier. However, it's worth considering that your bundle configuration might be importing global CSS from the node_modules directory. By addressing this, you can potentially overcome the issue. Could you share what solution have you found for this issue?

**Comment by OliverDudgeon** [comment] 2023-05-22 11:27
Does this not work for you?

import "ketcher-react/dist/index.css";

**Comment by OliverDudgeon** [comment] 2023-05-22 19:58
So this happens as a side-effect of importing from `ketcher-react`?

**Comment by michelmar** [comment] 2023-05-22 21:27
Yes, this is related to a these two libraries that has globall css imported in the ketcher-react packages

**Comment by OliverDudgeon** [comment] 2023-05-22 22:18
All I've done to make this work for me I create a component that uses `import { Editor } from "ketcher-react";`. Then to use this component, I do a  **dynamic** import (to avoid SSR differences). The only other thing that could be in play here is that I use pnpm? There isn't really anything in my nextjs config that I can see having an affect here.

**Comment by yuleicul** [comment] 2023-07-04 08:22
Hi @michelmar , did you try to use Ketcher inside `app/` directory? According to this comment https://github.com/vercel/next.js/discussions/27953#discussioncomment-3978605, NextJS 13 has supported global CSS inside `app/`.

**Comment by yuleicul** [comment] 2023-07-11 09:16
This is caused by NextJS, so we're gonna close it. If you believe that this is Ketcher's problem, please reopen the issue and give more information, thx!

**Closed by yuleicul** 2023-07-11 09:16 UTC
Labels: bug, feature request

**Comment by ahmepham** [comment] 2024-01-02 16:31
I avoided this message by adding moduleExports={ transpilePackages: ['draft']} to my next.config.js file
