### ISSUE TITLE
Last bracket in 'Calculated Values' is absent when Reaction is on the canvas.

### ISSUE THREAD

**Issue by KseniiaSemenishcheva** [epam/ketcher#293] opened 2021-02-08 07:57 UTC
**Affected Version:** _Remote_
**Preconditions:**
- Ketcher is launched.
- Reaction with multiple reactants and products is already created on canvas or [Reaction.zip](https://github.com/epam/ketcher/files/5942006/Reaction.zip) is opened.

**Steps to Reproduce:**
1. Click 'Calculated Values' button.

**Expected Result:**
In 'Chemical Formula' field '[C5H12] + [C6H6] > [C11H16]' correct reaction displays.

**Actual Result:**
Last bracket in 'Chemical Formula' field is absent. Response from Indigo is correct.
![BracketCalculatedValues](https://user-images.githubusercontent.com/75974465/107190807-55f92b00-69fc-11eb-9bd5-06df00a73200.jpg)

**Comment by AndreiMazol** [comment] 2021-03-09 14:54
Duplicate of https://github.com/epam/ketcher/issues/364

**Closed** 2021-03-09 14:54 UTC
Labels: bug, duplicate, low priority
