### ISSUE TITLE
3D view does not seem to work

### ISSUE THREAD

**Issue by KonstantinEpam23** [epam/ketcher#4647] opened 2024-05-17 18:15 UTC
**Steps to Reproduce**
1. Go to structure library, in "3D Templates" list - select the first item "fullerene C60", click on it and add to canvas
2. Click on "3D Viewer" button in the top panel

**Actual behavior**
The z coordinate is lost, the structure appears flat

**Expected behaviour**
Z axis coordinate is preserved, the structure appears as a 3d spherical molecular structure in Mview window

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: 123.0.6312.122 (Official Build) (arm64)

**Ketcher version** 
2.20.0

**Additional context**
https://lifescience.opensource.epam.com/KetcherDemoSA/index.html

**Comment by rrodionov91** [comment] 2024-05-17 20:21
Hi @KonstantinEpam23,

Thank you for raising the issue.

We already have fix for 2.22.0-rc.1
Here is a ticket https://github.com/epam/ketcher/issues/3501

I will close the issue as duplicate. If you have any objections please reopen it.

Thank you!

**Comment by rrodionov91** [comment] 2024-05-17 20:22
Duplicate of https://github.com/epam/ketcher/issues/3501

**Closed by rrodionov91** 2024-05-17 20:22 UTC
Labels: bug
