### ISSUE TITLE
Subscripted text shown as ordinary one (subscript is not applied)

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4138] opened 2024-02-23 10:27 UTC
**Steps to Reproduce**
1. Click Open... button (Ctrl+O)
2. Select open from file
3. Select file: [Subscript support.pptx](https://github.com/epam/ketcher/files/14386791/Subscript.support.pptx)
4. Click Open as New Project

**Actual behavior**
Subscripted text shown as ordinary one (subscript is not applied)
![image](https://github.com/epam/Indigo/assets/26869421/dfa4a042-5ea6-4ae4-ba54-1d2a325cd60e)

**Expected behavior**
Subscript is applied
![image](https://github.com/epam/Indigo/assets/26869421/ec5e2480-e2b1-423a-8be7-e58807e178c8)

**Environment details:**
- Ketcher Version 2.18.0-rc.5 Build at 2024-02-09; 17:07:18
- Indigo Toolkit Version 1.18.0-rc.6+cdx.0-g99f004a82-x86_64-linux-gnu-11.4.0
- Chrome Version Version 121.0.6167.161 (Official Build) (64-bit)
- Win10
- Issue found while testing https://github.com/epam/ketcher/issues/3914

**Comment by rrodionov91** [comment] 2024-02-23 13:41
Indigo sends next json in response:
<img width="912" alt="image" src="https://github.com/epam/ketcher/assets/14859362/d6d4fd14-0b39-46de-807b-284127f39171">

The problem is that Ketcher expects that in inlineStyleRanges first will be styles for entire row and after that some overrides for specific parts.
<img width="705" alt="image" src="https://github.com/epam/ketcher/assets/14859362/ae3c5b70-07d4-4faf-b707-896fb4c66dc0">

It needs to be fixed on Indigo side.

**Closed** 2024-02-23 15:21 UTC
Labels: bug, external, severity: Medium, ChemDraw
