### ISSUE TITLE
Duplicate on the Canvas while structures are Copied / Pasted

### ISSUE THREAD

**Issue by NadezhdaPeskun** [epam/ketcher#4709] opened 2024-05-29 12:59 UTC
**Steps to Reproduce**

1. Switch to Macro >> Flex or Snake mode
2. Open file 
[ketcher (8).zip](https://github.com/epam/ketcher/files/15187711/ketcher.8.zip)
<img width="317" alt="image" src="https://github.com/epam/ketcher/assets/161723514/062ee653-6d5a-43a4-b1e4-af2a1896c9a9">

**3. Switch to Micro >> Switch to Macro again**
4. Goto Sequence mode 
5. Select all >> Copy >> Paste

https://github.com/epam/ketcher/assets/161723514/6e8600fd-e850-461d-8b2c-bb0d82f0759a

**Actual behavior**
Duplicate on the Canvas while structures are Copied / Pasted.
![image](https://github.com/epam/ketcher/assets/161723514/24c4355b-1ea7-49ba-b5a5-1da034a32434)

**Expected behavior**
Duplicate should not appear on the Canvas while structures are Copied / Pasted.

**Versions:**
CI [Version 2.22.0-rc.1]

**Comment by NadezhdaPeskun** [comment] 2024-05-29 14:27
This Issue was found during verification of 
- https://github.com/epam/ketcher/issues/4568

**Comment by rrodionov91** [comment] 2024-06-05 09:23
Duplicate of https://github.com/epam/ketcher/issues/4708

**Closed by rrodionov91** 2024-06-05 09:23 UTC
Labels: bug, Priority: High, Macromolecules, Macro-Micro
