### ISSUE TITLE
Multiple bond editing changes bond types to all selected bonds

### ISSUE THREAD

**Issue by mwojcikowski** [epam/ketcher#2246] opened 2023-02-20 13:54 UTC
**Steps to Reproduce**
1. Select multiple bonds with mixed bond order.
![image](https://user-images.githubusercontent.com/2325645/220125816-50a093dd-b24b-43e5-920c-790e7c80c115.png)

2. Enter "edit" menu of the bonds. Optional: change reaction center or topology value.
![image](https://user-images.githubusercontent.com/2325645/220125970-6b4c9e9a-d738-4fb7-8829-813757269c58.png)

3. Save changes. Bond order has changed for entire selection.
![image](https://user-images.githubusercontent.com/2325645/220126161-40022283-8625-4db5-be8d-bda7429b853a.png)

The same happens if you enter edit with single bond:
![image](https://user-images.githubusercontent.com/2325645/220126303-42256cf3-487b-4059-b0d9-a38965a928e5.png)

**Expected behavior**
In edit bond window the bond order is unselected if mixed order bonds were selected. Saving changes should not change bond orders unless explicitly changed.

**Ketcher version** 
v2.7.1

**Comment by Zhirnoff** [comment] 2023-02-20 15:02
Hi @mwojcikowski thank you for using Ketcher! What exactly you mean "Bond order has changed for entire selection"?

**Comment by mwojcikowski** [comment] 2023-02-20 15:27
Hi @Zhirnoff,
What I meant is that the bonds are converted to single or double, depending on the bond you click to edit. Compare the images in 1 vs 3.

Hopefully this image is clearer. Top one is when you click on single bond. Bottom when on doulbe.
![image](https://user-images.githubusercontent.com/2325645/220146165-c58146ce-3522-4790-bb7b-02e227e3e3f8.png)

**Comment by mwojcikowski** [comment] 2023-02-20 15:30
Other software handles such issue, that the bond order is not set at all (or set to an empty value).
![image](https://user-images.githubusercontent.com/2325645/220146916-3063c286-18a3-4d80-b847-25c11c7379fc.png)

**Comment by Zhirnoff** [comment] 2023-02-20 16:03
@mwojcikowski Thanks for the more detailed information. We will try to fix this behavior in future releases.

**Comment by Zhirnoff** [comment] 2023-02-20 17:18
**Steps to Reproduce**
1. Open Ketcher
2. Add structure on canvas [ketcher (42).zip](https://github.com/epam/ketcher/files/10786313/ketcher.42.zip)
3. Highlight the top of the structure with a double bond and single bonds
4. Double click on Double bond
5. Select 'Topology'=Ring and press Apply

**Actual behavior**
Topology is assigned to all selected bonds, but single bonds became double

**Expected behavior**
Topology is assigned to all selected bonds, single bonds have not changed

Note: This behavior is due to the fact that during multiple selection and further editing in the 'Bond Properties' window, the type of bond is already selected, which is applied to the multiselect.

**Screenshots**


https://user-images.githubusercontent.com/62464241/220167659-7a162c9d-8893-4de4-b4e7-5e28e2440c5c.mp4








**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 109.0.5414.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.8.0-rc.3](https://lifescience.opensource.epam.com/ketcher/index.html)

**Additional context**

**Closed** 2023-04-04 08:43 UTC
Labels: bug
