### ISSUE TITLE
Stereo labels not disappear if User delets stereo bonds or atom with stereo bond.

### ISSUE THREAD

**Issue by KseniiaSemenishcheva** [epam/ketcher#209] opened 2020-12-28 07:21 UTC
**Affected Version:** _Standalone, Remote_
**Steps to Reproduce:**
1. Open 'structure_with_stereo_bonds.mol', for example.
2. Click 'Calculate CIP' button.
3. Click on 'Erase' tool and delete stereo bonds.
4. Delete bond between stereo labels.

**Expected Result:**
When User delete stereo bond stereo label should disappear.

**Actual Result:**
After deleting stereo bond stereo label still displays on canvas.
![1](https://user-images.githubusercontent.com/75974465/103197063-6a72df80-48f6-11eb-9925-0d7474d276a3.jpg)
![2](https://user-images.githubusercontent.com/75974465/103197064-6b0b7600-48f6-11eb-8701-b1ef48928bf3.jpg)

**Comment by TomasLight** [comment] 2021-02-26 09:28
When we call CIP calculation, it request structure from the server, but when we erase lines there is not server reques and we don't know about sgroup forest changes.
This labels is rendered from `restruct/index.js -> ReStruct.prototype.showSGroups`.

So here is two options for resolving this bug:
1) request server each time on erasing
2) place logic on a frontned part

**Comment by MagomedGasanov** [comment] 2021-04-20 09:54
duplicated with https://github.com/epam/ketcher/issues/195

**Comment by Svetlana-Asinovskaia** [comment] 2021-05-28 15:15
Release/2.3 The issue is closed as duplicate. Will be fixed in https://github.com/epam/ketcher/issues/539

**Closed by Svetlana-Asinovskaia** 2021-05-28 15:15 UTC
Labels: bug, duplicate, epic: enhanced stereochemistry
