### ISSUE TITLE
Do/Undo loginc doesn't save Flex to Sequence mode switch as an action and doesn't undo it

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5068] opened 2024-07-10 13:46 UTC
**NOTE:** Probably the same root cause with https://github.com/epam/ketcher/issues/5048 and https://github.com/epam/ketcher/issues/5049

**Steps to Reproduce**
1. Go to Macromolecules - Flex mode <---Important!
2. Load from file: [Do-Undo loginc doesn't save Flex to Sequence mode switch as an action and doesn't undo it.zip](https://github.com/user-attachments/files/16163008/Do-Undo.loginc.doesn.t.save.Flex.to.Sequence.mode.switch.as.an.action.and.doesn.t.undo.it.zip)
![image](https://github.com/epam/ketcher/assets/26869421/ca4879be-49c5-4a96-b560-fd56cfbc56f0)
3. Delete some chains
![image](https://github.com/epam/ketcher/assets/26869421/57c5b564-9be3-4a23-9d3a-4a1027d7bd92)
4. Switch view to Sequence mode
![image](https://github.com/epam/ketcher/assets/26869421/8dccd2cb-e161-4223-8122-2aeb8e292870)
5. Press Undo button

**Actual behavior**
No switch to Flex mode happens, system restores deleted chains
![image](https://github.com/epam/ketcher/assets/26869421/12f78e24-6b66-46c6-bdc9-4bd9e571d8d3)

**Expected behavior**
System switches to Flex mode
![image](https://github.com/epam/ketcher/assets/26869421/f00a565d-64ac-4d6a-a82b-bedfec385a69)

**Environment details:**
- Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 09:03:38
- Indigo Toolkit Version 1.21.0-rc.3.0-g1570d3f9f-x86_64-linux-gnu-11.2.1
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/ketcher/issues/3532

**Comment by svvald** [comment] 2024-08-08 14:51
Can't reproduce, probably fixed by https://github.com/epam/ketcher/issues/5049 as having common root cause

**Closed by svvald** 2024-08-08 14:51 UTC
Labels: bug, Priority: High, Sequence mode, Common UI problems, Flex mode

**Comment by Zhirnoff** [comment] 2024-08-15 13:04
Tested. Bug fixed.


https://github.com/user-attachments/assets/c9a0d05d-7b7c-4a7f-9d33-8c628b941f04


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 127.0.6533.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.24.0-rc.2]
**Indigo version** 
[Version 1.23.0-rc.2]
