### ISSUE TITLE
Buttons 'Cut', 'Copy' and shortcuts for Cut, Copy and Paste do not work in IE11

### ISSUE THREAD

**Issue by ElenaKlepova** [epam/ketcher#232] opened 2020-12-30 08:36 UTC
**Affected version:** Release/2.1

**Browser:** IE 11.630.19041.0

**Steps to reproduce:**
1. Create a structure.
2. Select the created structure.
3. Click 'Cut' button or use shortcut Crtl+X.
4. Click 'Copy' button or use shortcut Crtl+C.
5. Click 'Paste' button or use shortcut Ctrl+V.

**Actual result:**
The created structure is not cut, copied and pasted. 
Buttons 'Cut', 'Copy' and shortcuts for Cut, Copy and Paste do not work. 
When clicking 'Paste' button 'This action is unavailable via menu. Instead, use shortcut to Paste.' is not shown.
![2020-12-30_11h33_05](https://user-images.githubusercontent.com/75974843/103339703-2832d500-4a93-11eb-912b-8376ff38a668.gif)

**Expected result:**
The created structure is cut, copied and pasted. 
Buttons 'Cut', 'Copy' and shortcuts for Cut, Copy and Paste work in IE11.
When clicking 'Paste' button 'This action is unavailable via menu. Instead, use shortcut to Paste.' is shown.

**Comment by AndreiMazol** [comment] 2021-03-26 14:42
Cannot reproduce. I guess the issue has been fixed in scope of another issue.

**Closed** 2021-03-26 14:42 UTC
Labels: bug, low priority

**Comment by Svetlana-Asinovskaia** [comment] 2021-03-26 14:54
Cannot reproduce. Tested in release/2.2
