### ISSUE TITLE
Input field is displayed when the size of the ketcher is changed

### ISSUE THREAD

**Issue by bodyangug** [epam/ketcher#1964] opened 2022-12-20 14:21 UTC
**Steps to Reproduce**
1. Change size of the ketcher
2. Check input field behind it.

**Actual behavior**
When I put a catcher in the frame of my application, I see an input field behind the ketcher.

**Expected behavior**
Input field should not be showed

**Screenshots**
<img width="1604" alt="image" src="https://user-images.githubusercontent.com/55767250/208687229-75926062-3b9c-4d2f-b419-58b47c7040cc.png">

**Comment by Nitvex** [comment] 2022-12-20 14:41
@bodyangug! Thanks for reporting an issue, but it seems to be a duplicate of https://github.com/epam/ketcher/issues/1835
So, closing this as duplicate.

**Closed by Nitvex** 2022-12-20 14:41 UTC
Labels: bug, feature request
