### ISSUE TITLE
Chiral flag should be removed when all Up/Down stereobonds are removed

### ISSUE THREAD

**Issue by Vesdet** [epam/ketcher#61] opened 2020-10-12 13:21 UTC
**Steps to reproduce:**
1. Launch Editor.
2. Create any chiral structure.
3. Change all Up/Down stereobonds with Simple bonds.

**Expected result:**
Chiral flag disappears when all Up/Down stereobonds are removed.

**Actual result:**
Chiral flag stays at the canvas when all Up/Down stereobonds are removed.

Epic link: #56

**Comment by irinatelnova** [comment] 2021-03-25 08:55
No change required, the issue was fixed as part of other tasks

**Comment by Svetlana-Asinovskaia** [comment] 2021-04-02 13:40
There is a problem with stereoflags after performing undo action.
1. Create any chiral structure.
2. Change one Up/Down stereobond with Simple bond.
3. Click 'Undo' button.

Expected result: Chiral flag remains as it was in the original structure.
Actual result: Chiral flag is changed into 'Mixed'.
![Chiral](https://user-images.githubusercontent.com/80695128/113419543-54325f00-93d0-11eb-8b49-33920d0bbb08.gif)

**Comment by Svetlana-Asinovskaia** [comment] 2021-04-06 08:20
'Undo' (and 'Redo') option with deleted stereobond works in two steps. 1st click - Stereolabel is returned to the canvas. 2nd click - stereobond is returned to the canvas.
Steps to reproduce:
1. Add a structure on the canvas (e.g. one of α-D-Sugars from Custom templates).
2. Click on 'Calculate CIP' button.
3. Delete one of stereobonds.
4. Click 'Undo' button.

**Comment by irinatelnova** [comment] 2021-04-15 14:35
CIP Calculation works on demand: after structure changing user should click the 'Calculate CIP' button once again to re-calculate stereoconfiguration (see this issue https://github.com/epam/ketcher/issues/195)
Now **Actual Result**:
'Undo' (and 'Redo') option with deleted stereobond (see steps to reproduce in the comment above) works in one step.
Changing structure action is merged with cip marks clearing in the history stack.

**Comment by Svetlana-Asinovskaia** [comment] 2021-05-04 15:09
The Chiral flag is removed after delete-undo actions.

Steps to reproduce:
1. Choose a structure with stereobonds from the Custom templates (e.g. a-D-Allopyranose).
2. Delete it with the 'Erase' tool or with the 'Delete' key.
3. Click the 'Undo' button.

Expected result: The structure with a chiral flag is present on the canvas.
Actual result: The structure without a chiral flag is present on the canvas.
![2021-05-04_18h07_46](https://user-images.githubusercontent.com/80695128/117025579-b4842b80-ad03-11eb-94cd-90f7bb18a1ef.gif)

**Closed** 2021-06-03 15:32 UTC
Labels: enhancement, epic: enhanced stereochemistry

**Comment by Svetlana-Asinovskaia** [comment] 2021-06-07 09:18
Release/2.3 The issue is closed as partly fixed. A scenario with the non-disappearing stereocenters in the case of replacement of the stereobonds with the double cis/trans bonds or the dative bonds is described in #554 and will be fixed within this task.
